repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/sbrunner/jsonschema2md
    rev: 0.9.0
    hooks:
      - id: jsonschema2md
        files: ms2rescore/package_data/config_schema.json
        args:
          - ms2rescore/package_data/config_schema.json
          - docs/source/config_schema.md
