{% set data = load_setup_py_data() %}

package:
  name: ms2rescore
  version: {{ data.get('version') }}

source:
  path: ./

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - ms2rescore=ms2rescore:main

requirements:
  host:
    - python 3.7
    - numpy >=1.15
    - pip
    - setuptools
  run:
    - python 3.7
    - pyteomics >=4.1
    - numpy >=1.15
    - pandas >=0.23.4
    - scipy >=1.1
    - scikit-learn >=0.20.1
    - tqdm >=4.28.1
    - xmltodict >=0.12.0

#test:
#  commands:
#    - python setup.py test

about:
  home: "{{ data.get('url') }}"
  license: APACHE
  license_file: LICENSE
  summary: "{{ data.get('description') }}"

extra:
  identifiers:
    - doi:10.1101/428805